### ISSUE TITLE
發現bug find bug

### ISSUE THREAD

**Issue by b510858** [gkbm2013/tinker-IO#1]
我發現了2個bug(目前)
1.在smart output中的錠會在shift+左鍵下變成64個
2.你能放東西進去smart output的成品位置
3.在smart output中的錠在會突然雙倍化

i find two bug new
1.the ingot in smart output will become when you shift+left click it
3.you can put thing in the output of smart output and shift+leftclick it
2.the ingot in smart output will double at some time

**Comment by gkbm2013** [comment]
Okay~ I have already fixed it! Thanks for your report!
我已經修好了~感謝你的回報!
