### ISSUE TITLE
[BUG]閃退...

### ISSUE THREAD

**Issue by killingwing02** [gkbm2013/tinker-IO#11]
點開Fuel Input Machine，在未放入任何東西的情形下把滑鼠移動到右上角的資訊(<!>)會導致閃退...是我的問題嗎?

**Comment by gkbm2013** [comment]
...<！>資訊是fuel input machine 才有…話說你有crash report 嗎？

**Comment by killingwing02** [comment]
呃...打錯了...我的狀況是是直接閃退，Crash Report我現在可能沒辦法看...要等明天，我明天順便附上MOD列表

**Comment by killingwing02** [comment]
...那啥，crash report好長一串...上次閃退沒有crash report...我用JAVA.EXE啟動後才有的，不知道是不是正確...
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 2015/6/19 上午 9:10
Description: Rendering screen

java.lang.NoSuchMethodError: tinker_io.gui.FIMGui.drawHoveringText(Ljava/util/List;IILnet/minecraft/client/gui/FontRenderer;)V
    at tinker_io.gui.FIMGui.func_146979_b(FIMGui.java:49)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:989)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at tinker_io.gui.FIMGui.func_146979_b(FIMGui.java:49)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:119)

-- Screen render details --
Details:
    Screen name: tinker_io.gui.FIMGui
    Mouse location: Scaled: (491, 168). Absolute: (983, 650)
    Screen size: Scaled: (840, 494). Absolute: (1680, 988). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['killing'/122, l='MpServer', x=1053.78, y=57.62, z=-600.63]]
    Chunk stats: MultiplayerChunkCache: 289, 298
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (1018,4,-576), Chunk: (at 10,0,0 in 63,-36; contains blocks 1008,0,-576 to 1023,255,-561), Region: (1,-2; contains chunks 32,-64 to 63,-33, blocks 512,0,-1024 to 1023,255,-513)
    Level time: 103116 game time, 462920 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 21 total;
[EntityBat['蝙蝠'/97, l='MpServer', x=978.22, y=35.00, z=-591.38],
EntityBat['蝙蝠'/98, l='MpServer', x=974.78, y=35.00, z=-593.66],
EntityWaypointContainer['未知'/264, l='MpServer', x=0.00, y=0.00, z=0.00],
EntityZombie['殭屍'/265, l='MpServer', x=985.50, y=35.00, z=-641.50],
EntityBat['蝙蝠'/106, l='MpServer', x=988.78, y=35.00, z=-657.94],
EntityCreeper['苦力怕'/107, l='MpServer', x=989.50, y=35.00, z=-648.50],
EntitySpider['蜘蛛'/267, l='MpServer', x=996.44, y=35.00, z=-641.75],
EntitySkeleton['骷髏'/236, l='MpServer', x=990.22, y=35.00, z=-664.00],
EntityCreeper['苦力怕'/109, l='MpServer', x=985.06, y=35.00, z=-643.66],
EntityBat['蝙蝠'/110, l='MpServer', x=990.56, y=35.00, z=-640.06],
EntityZombie['殭屍'/111, l='MpServer', x=991.89, y=34.35, z=-637.24],
EntityChicken['雞'/112, l='MpServer', x=991.84, y=34.00, z=-637.16],
EntityCreeper['苦力怕'/113, l='MpServer', x=986.03, y=35.00, z=-643.28],
EntitySpider['蜘蛛'/114, l='MpServer', x=986.91, y=34.00, z=-637.91],
EntityCreeper['苦力怕'/115, l='MpServer', x=992.13, y=35.00, z=-641.72],
EntitySkeleton['骷髏'/243, l='MpServer', x=984.72, y=34.00, z=-600.72],
EntityCreeper['苦力怕'/116, l='MpServer', x=985.00, y=35.00, z=-642.50],
EntityZombie['殭屍'/279, l='MpServer', x=1000.93, y=35.00, z=-643.05],
EntityCreeper['苦力怕'/90, l='MpServer', x=974.50, y=33.00, z=-638.50], EntityClientPlayerMP['killing'/122, l='MpServer', x=1053.78, y=57.62, z=-600.63],
EntitySkeleton['骷髏'/127, l='MpServer', x=990.50, y=35.00, z=-660.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (x86) version 6.1
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 181675744 bytes (173 MB) / 556249088 bytes (530 MB) up to 1037959168 bytes (989 MB)
    JVM Flags: 2 total; -Xmx673m -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 Optifine OptiFine_1.7.10_HD_U_B5 38 mods loaded, 38 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge](forge-1.7.10-10.13.2.1291.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.35} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    uniskinmod{1.2-dev3} [Universal Skin Mod](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DamageIndicatorsMod{3.2.0} [Damage Indicators](%5B1.7.10%5DDamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-262.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights{1.3.7} [Dynamic Lights](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IC2{2.2.667-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.667-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks](InventoryTweaks-1.59-dev-156.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IronChest{6.0.62.742} [Iron Chest](Iron-Chests-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.8} [Waila](Waila-1.5.9_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherOres{1.7.10R2.3.0RC4} [Nether Ores](NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0-81 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.1-182 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.8.3.build919} [Tinkers' Construct](TConstruct-1.7.10-1.8.3b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.0.0-122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TiCTooltips{1.2.3} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    tinker_io{beta 1.1.3} [Tinker I/O](tinker_io-1.7.10-beta1.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    voxelmap{1.7.10} [VoxelMap No Radar](Zans-Minimap-No-Radar-Mod-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IguanaTweaksTConstruct{1.7.10-2.1.4.132} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore: -[1.7.10]3.0.2-262
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    NetherOres: Lacking version information.
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    TConstruct Environment: Environment healthy.
    ThermalDynamics: -[1.7.10]1.0.0-122
    Launched Version: 1.7.10-Forge10.13.2.1291_OptiFine
    LWJGL: 2.9.1
    OpenGL: GeForce GT 630/PCIe/SSE2/3DNOW! GL version 4.5.0 NVIDIA 353.06, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [XXX.zip]
Current Language: 繁體中文 (台灣)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

---

我把材質包名字刪掉了...因為不重要...還有一堆生物那邊我幫他分段了...接下來是MOD，雖然上面有了不過還是給一下...
/mods

[1.7.10]DamageIndicatorsMod-3.2.0(血量顯示)
CodeChickenCore-1.7.10-1.0.4.35-universal
CoFHCore-[1.7.10]3.0.2-262
DynamicLights-1.7.10(動態光源)
fastcraft-1.21(MC優化)
IguanaTinkerTweaks-1.7.10-2.1.4(工具升級)
industrialcraft-2-2.2.667-experimental(IC2)
InventoryTweaks-1.59-dev-156(整理包包)
Iron-Chests-Mod-1.7.10(鐵箱子)
Jabba-1.2.1a_1.7.10(JABBA)
Mantle-1.7.10-0.3.2
NetherOres-[1.7.10]2.3.0RC4-4(地獄礦物)
NotEnoughItems-1.7.10-1.0.4.83-universal(NEI)
TConstruct-1.7.10-1.8.3b(匠魂)
Thaumcraft-1.7.10-4.2.3.5(奇術4)
ThermalDynamics-[1.7.10]1.0.0-122
ThermalExpansion-[1.7.10]4.0.1-182
ThermalFoundation-[1.7.10]1.0.0-81
TiCTooltips-mc1.7.10-1.2.3(TC工具更多資訊)
tinker_io-1.7.10-beta1.1.3(實測用1.2.0最新版也會閃退)
UniSkinMod-1.7.10-1.2-dev3-rev2(Skin...恩，還沒有錢...)
Waila-1.5.9_1.7.10
Zans-Minimap-No-Radar-Mod-1.7.10(Zan's小地圖無雷達版)

/mods/1.7.10

[1.7.10]bspkrsCore-universal-6.15
Baubles-1.7.10-1.0.1.10
CodeChickenLib-1.7.10-1.1.1.99-universal

/mods/for development

DynamicLights_dummy

/mods/ic2

ejml-0.23

/mods/VoxelMods

voxelmap.properties

/1.7.10-Forge10.13.2.1291_OptiFine.jar

OptiFine_1.7.10_HD_U_B5

電腦資訊

其實上面也有...打個簡單的...

Win7 x86 2cpu 2GRAM
GeForce GT 630
Java1.8.0_45

基本上就醬...
超長一串...

**Comment by gkbm2013** [comment]
好...我會在下一個版本修復的...
感謝你的回報!

**Comment by gkbm2013** [comment]
已於Beta 1.2.1 修復完成!
http://minecraft.curseforge.com/mc-mods/229503-tinker-i-o/files/2243563
