### ISSUE TITLE
未知崩潰

### ISSUE THREAD

**Issue by axzxc1236** [gkbm2013/tinker-IO#12]
[崩潰報告](http://pastebin.com/x7CubsYb)
這個崩潰會導致地圖無法被開啟
崩潰之後我在地圖的chunk檔裡面發現[這個](http://i.imgur.com/OLsDUuk.png)

無可奈何我們只好從伺服器移除Tinker I/O　因為不知道會不會再發生一次

**Comment by gkbm2013** [comment]
Tinker I/O beta 1.3.0 hotfix III 已經修復這個問題了，感謝你的回報!
