### ISSUE TITLE
class not found? waila-tinker-io 

### ISSUE THREAD

**Issue by PlatinumEragong** [gkbm2013/tinker-IO#16]
---- Minecraft Crash Report ----
// Sorry :(

Time: 12/8/15 3:38 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.ClassNotFoundException: tinker_io.plugins.waila.MainWaila
    at com.google.common.base.Throwables.propagate(Throwables.java:160)
    at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:76)
    at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554)
    at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: tinker_io.plugins.waila.MainWaila
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:340)
    at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
    ... 7 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 12 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Linux (amd64) version 2.6.32-042stab106.4
    Java Version: 1.8.0_05, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 259584768 bytes (247 MB) / 1002438656 bytes (956 MB) up to 1990197248 bytes (1898 MB)
    JVM Flags: 11 total; -XX:+OptimizeStringConcat -XX:OnOutOfMemoryError=curl https://api.creeper.host/callbacks/minecraft/outofmemory.php?instance=mc-565e3dcf79043 -k -XX:OnError=curl https://api.creeper.host/callbacks/minecraft/crash.php?instance=mc-565e3dcf79043 -k -XX:-UseCompressedOops -Xmx2168M -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:ParallelGCThreads=2 -XX:+AggressiveHeap -XX:+AggressiveOpts -XX:MaxMetaspaceSize=256M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 164 mods loaded, 164 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UC  Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UC  appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UC  CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
    UC  MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) 
    UC  MobiusCore{1.2.5} [MobiusCore](minecraft.jar) 
    UC  technomCore{0.12.0A} [Technomancy Core](minecraft.jar) 
    UC  WitchingGadgetsCore{1.1.10} [Witching Gadgets Core](minecraft.jar) 
    UC  OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UC  <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UC  IC2{2.2.628-experimental} [IndustrialCraft 2](_Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
    UC  appliedenergistics2{rv2-stable-10} [Applied Energistics 2](appliedenergistics2-rv2-stable-10.jar) 
    UC  bdlib{1.9.3.107} [BD Lib](bdlib-1.9.3.107-mc1.7.10.jar) 
    UC  ae2stuff{0.5.0.56} [AE2 Stuff](ae2stuff-0.5.0.56-mc1.7.10.jar) 
    UC  AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) 
    UC  Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UC  Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) 
    UC  arcanearteries{5} [Arcane Arteries](ArcaneArteries0.7.2.jar) 
    UC  CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UC  MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    UC  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UC  Automagy{0.27} [Automagy](Automagy-1.7.10-0.27.jar) 
    UC  BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
    UC  ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UC  ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UC  BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
    UC  Mantle{1.7.10-0.3.2.jenkins191} [Mantle](Mantle-1.7.10-0.3.2b.jar) 
    UC  Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) 
    UC  BiomesOPlenty{2.1.0} [Biomes O' Plenty](BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar) 
    UC  AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.3-17.jar) 
    UC  Botania{r1.7-236} [Botania](Botania r1.7-236.jar) 
    UC  ForbiddenMagic{1.7.10-0.571} [Forbidden Magic](Forbidden Magic-1.7.10-0.571.jar) 
    UC  guideapi{1.7.10-1.0.1-20} [Guide-API](Guide-API-1.7.10-1.0.1-20.jar) 
    UC  ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UC  BuildCraft|Core{7.1.13} [BuildCraft](buildcraft-7.1.13.jar) 
    UC  ExtraUtilities{1.2.12} [Extra Utilities](extrautilities-1.2.12.jar) 
    UC  TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
    UC  BloodArsenal{1.2-4} [Blood Arsenal](BloodArsenal-1.7.10-1.2-4.jar) 
    UC  BrandonsCore{1.0.0.10} [Brandon's Core](BrandonsCore-1.0.0.10-bugfix.jar) 
    UC  BuildCraft|Builders{7.1.13} [BC Builders](buildcraft-7.1.13.jar) 
    UC  BuildCraft|Transport{7.1.13} [BC Transport](buildcraft-7.1.13.jar) 
    UC  BuildCraft|Energy{7.1.13} [BC Energy](buildcraft-7.1.13.jar) 
    UC  BuildCraft|Silicon{7.1.13} [BC Silicon](buildcraft-7.1.13.jar) 
    UC  BuildCraft|Robotics{7.1.13} [BC Robotics](buildcraft-7.1.13.jar) 
    UC  BuildCraft|Factory{7.1.13} [BC Factory](buildcraft-7.1.13.jar) 
    UC  Forestry{4.2.1.48} [Forestry for Minecraft](forestry_1.7.10-4.2.1.48.jar) 
    UC  BuildCraft|Compat{7.1.2} [BuildCraft Compat](buildcraft-compat-7.1.2.jar) 
    UC  CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UC  ChickenChunks{1.3.4.19} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UC  Railcraft{9.8.0.0} [Railcraft](Railcraft_1.7.10-9.8.0.0.jar) 
    UC  chisel{2.9.3.9} [Chisel](Chisel-2.9.3.9.jar) 
    UC  ComputerCraft{1.74} [ComputerCraft](ComputerCraftPlusComputerCraftEdu1.74.jar) 
    UC  ComputerCraftEdu{1.74} [ComputerCraftEdu](ComputerCraftPlusComputerCraftEdu1.74.jar) 
    UC  D3Core{1.1.0.31} [D3Core](D3Core-1.7.10-1.1.0.31.jar) 
    UC  DraconicEvolution{1.0.2-snapshot_7} [Draconic Evolution](Draconic-Evolution-1.7.10-1.0.2-Snapshot_7-bugfix.jar) 
    UC  DummyCore{1.13} [DummyCore](DummyCore1.13.jar) 
    UC  Enchiridion{1.1} [Enchiridion](Enchiridion-1.7.X-1.2b.jar) 
    UC  endercore{1.7.10-0.2.0.31_beta} [EnderCore](EnderCore-1.7.10-0.2.0.31_beta.jar) 
    UC  MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) 
    UC  Mekanism{8.1.7} [Mekanism](Mekanism-1.7.10-8.1.7.252.jar) 
    UC  EnderIO{1.7.10-2.2.8.381} [Ender IO](EnderIO-1.7.10-2.2.8.381.jar) 
    UC  EnderStorage{1.4.7.37} [EnderStorage](EnderStorage-1.7.10-1.4.7.37-universal.jar) 
    UC  Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) 
    UC  ExtraTiC{1.4.5} [ExtraTiC](ExtraTiC-1.7.10-1.4.5.jar) 
    UC  FastCraft{1.21} [FastCraft](fastcraft-1.21.jar) 
    UC  fastleafdecay{1.3} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.3.jar) 
    UC  FloodLights{0.6.11-103} [Flood Lights](FloodLights-1.7.10-0.6.11-103.jar) 
    UC  gadomancy{1.0.5} [Gadomancy](gadomancy-1.7.10-1.0.5.jar) 
    UC  RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UC  MagicBees{1.7.10-2.4.0} [Magic Bees](magicbees-1.7.10-2.4.0.jar) 
    UC  gendustry{1.6.2.127} [GenDustry](gendustry-1.6.2.127-mc1.7.10.jar) 
    UC  GraveStone{2.15.2} [GraveStone](GraveStone-2.15.2.jar) 
    UC  iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UC  inpure|core{1.7.10R1.0.0B9} [INpureCore](INpureCore-[1.7.10]1.0.0B9-62.jar) 
    UC  integratedcircuits{1.7.10-0.9r37c} [Integrated Circuits](integratedcircuits-1.7.10-0.9r37c.jar) 
    UC  intellie{2.1.4.554} [IntelliE](IntelligentEnergistics-1.7.10-2.1.4.554-universal.jar) 
    UC  appaero{2.1.4.554} [AppliedAerodynamics](IntelligentEnergistics-1.7.10-2.1.4.554-universal.jar) 
    U   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    U   LogisticsPipes{0.9.3.69} [Logistics Pipes](logisticspipes-0.9.3.69.jar) 
    U   magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.2-0.11.jar) 
    U   Mariculture{1.7.10-1.2.4.2a} [Mariculture](Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
    U   MariTech{1.0} [Marine Technlogy](Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
    U   MekanismGenerators{8.1.7} [MekanismGenerators](MekanismGenerators-1.7.10-8.1.7.252.jar) 
    U   MekanismTools{8.1.7} [MekanismTools](MekanismTools-1.7.10-8.1.7.252.jar) 
    U   minechem{5.0.5.406} [Minechem](Minechem-1.7.10-5.0.5.406.jar) 
    U   MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MrTJPCoreMod{1.1.0.31} [MrTJPCore](MrTJPCore-1.7.10-1.1.0.31-universal.jar) 
    U   ProjRed|Core{4.7.0pre9.92} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
    U   MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
    U   MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) 
    U   mobopt{0.9} [Mob Options](MobOptions-0.9.jar) 
    U   modtweaker2{0.9.4} [Mod Tweaker 2](ModTweaker2-0.9.4.jar) 
    U   SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways](SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
    U   morechisels{@VERSION@} [More Chisels](MoreChisels-1.7.10-1.0-28.jar) 
    U   Morph{0.9.2} [Morph](Morph-Beta-0.9.2.jar) 
    U   Morpheus{1.7.10-1.6.18} [Morpheus](Morpheus-1.7.10-1.6.18.jar) 
    U   NetherOres{1.7.10R2.3.0} [Nether Ores](NetherOres-[1.7.10]2.3.0-12.jar) 
    U   NodalMechanics{1.7.10R1.0} [NodalMechanics](NodalMechanics-1.7-1.0-7.jar) 
    U   OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    U   OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar) 
    U   MapWriter{2.1.2} [MapWriter](Opis-1.2.5_1.7.10.jar) 
    U   Opis{1.2.5} [Opis](Opis-1.2.5_1.7.10.jar) 
    U   origin{7.1.0} [Origin](Origin-1.7.10-7.1.0.jar) 
    U   PowerConverters3{1.7.10-2.11} [Power Converters 3](PowerConverters-1.7.10-2.11.jar) 
    U   ProjectE{1.7.10-PE1.9.4} [ProjectE](ProjectE-1.7.10-PE1.9.4.jar) 
    U   ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    U   ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
    U   ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    U   ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
    U   Quadrum{1.2.0} [Quadrum](Quadrum-1.7.10-1.2.0.B13-universal.jar) 
    U   reborncore{1.1.0.15} [RebornCore](RebornCore-1.1.0.15-universal.jar) 
    U   rftools{4.13} [RFTools](rftools-4.13.jar) 
    U   AS_Ruins{14.6} [Ruins Spawning System](Ruins-1.7.10.jar) 
    U   Sanguimancy{1.7.10-1.1.9-31} [Sanguimancy](Sanguimancy-1.7.10-1.1.9-31.jar) 
    U   secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod-1.7.10-4.7.1.406.jar) 
    U   SimilsaxTranstructors{1.7.10.11} [Similsax Transtructors](SimilsaxTranstructors-1.7.10.11.jar) 
    U   StevesFactoryManager{A93} [Steve's Factory Manager](StevesFactoryManagerA93.jar) 
    U   StevesAddons{0.10.16} [Steve's Addons](StevesAddons-1.7.10-0.10.16.jar) 
    U   supercraftingframe{1.7.10.3} [Super Crafting Frame](supercraftingframe-1.7.10.3.jar) 
    U   TaintedMagic{1.1.6.4} [Tainted Magic](TaintedMagic-1.1.6.4.jar) 
    U   techreborn{0.7.1.1056} [TechReborn](TechReborn-0.7.1.1056-universal.jar) 
    U   benway_knowledge{0.1.5.1} [Thaumaturgical Knowledge](Thaumaturgical Knowledge-0.1.5.1.jar) 
    U   thaumcraftgates{1.4.2} [Thaumcraft Gates](ThaumcraftGates-1.4.2.jar) 
    U   ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) 
    U   TU{1.0} [Thaumic Upholstry](Thaumic_Upholstery-1.2_1.7.10.jar) 
    U   thaumicbases{1.3.1710.2} [Thaumic Bases](ThaumicBases-1.3.1710.4.jar) 
    U   thaumicexpansion{4.1.1} [Thaumic Expansion](ThaumicExpansion-1.7.10-4.1.1.jar) 
    U   ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.7.10-1.1-53.jar) 
    U   thaumicinfusion{4.32} [Thaumic Infusion](ThaumicInfusion-4.32.jar) 
    U   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    U   ThermalSmeltery{1.7.10-1.2.1} [Thermal Smeltery](ThermalSmeltery-1.7.10-1.2.1.jar) 
    U   tinker_io{beta 1.4.2} [Tinker I/O](tinker_io-1.7.10-beta 1.4.2.jar) 
    U   TMechworks{0.2.14.100} [Tinkers' Mechworks](TMechworks-1.7.10-0.2.14.100.jar) 
    U   TravellersGear{1.16.6} [Traveller's Gear](TravellersGear-1.7.10-1.16.6.jar) 
    U   VeinMiner{0.30.0_build.unknown} [Vein Miner](VeinMiner-1.7.10_0.30.0.unknown.jar) 
    U   VeinMinerModSupport{0.30.0_build.unknown} [Mod Support](VeinMiner-1.7.10_0.30.0.unknown.jar) 
    U   veinminermodintegration{1.7.10-0.2.0} [Veinminer Mod Integration](veinminermodintegration-1.7.10-0.4.2.unknown.jar) 
    U   WailaHarvestability{1.1.5} [Waila Harvestability](WailaHarvestability-mc1.7.10-1.1.5.jar) 
    U   witchery{0.24.1} [Witchery](witchery-1.7.10-0.24.1.jar) 
    U   WitchingGadgets{1.1.10} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.10.jar) 
    U   WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    U   WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    U   WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    U   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    U   IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    U   technom{0.12.0A} [Technomancy](Technomancy - 0.12.1C - 1.7.10.jar) 
    U   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[map_gen_fix:ENABLED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
    Class transformer null safety: all safe
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.3-303
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    RedstoneArsenal: -[1.7.10]1.1.1-89
    Profiler Position: N/A (disabled)
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by gkbm2013** [comment]
I will fix the bug in next version ! Thanks for your report!

**Comment by gkbm2013** [comment]
Sorry... I found it's not a problem cause by Tinker I/O...

**Comment by PlatinumEragong** [comment]
can you make possible to have a server only version.... i wanna have a mod on my server which not need waila and nei ._. because my server hates client only mods
