### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by coin3x** [gkbm2013/tinker-IO#17]
mudpack -> modpack
超值泥土套餐(X

**Comment by gkbm2013** [comment]
話說人生在世老馬在所難免... (?
回歸正題...
可以告訴我這行錯字出現在哪裡嗎?
謝謝~

**Comment by coin3x** [comment]
Readme.md 第八行
It is fine to use Tinker I/O into your mudpack.

**Comment by gkbm2013** [comment]
我了解了，謝謝回報!
