### ISSUE TITLE
[1.10.2] Server crash on load

### ISSUE THREAD

**Issue by C0rn3j** [gkbm2013/tinker-IO#18]
Client forge 2014 - loads, server 2014 - crashes.

Modlist: http://pastebin.com/RKFKHpCw

Full crashlog: http://pastebin.com/GzAvTMWY

**Comment by gkbm2013** [comment]
I had fixed the problem!
Thanks!
http://minecraft.curseforge.com/projects/tinker-i-o/files/2317333

**Comment by C0rn3j** [comment]
Does not work, still crashes.

http://pastebin.com/fnmRbFCv

**Comment by gkbm2013** [comment]
Sorry for update frequently...
I had test the last version in my computer. Hope it can work...
Here is the last version : 
tinker_io-1.10.2-beta 2.3.2**b**
http://minecraft.curseforge.com/projects/tinker-i-o/files/2317333

**Comment by C0rn3j** [comment]
Loaded on both, thanks.
