### ISSUE TITLE
[1.10.2] Small visual bug with Actuality Addition crates when near Fuel input machine

### ISSUE THREAD

**Issue by Gayanfalor** [gkbm2013/tinker-IO#22]
Hello, 

Im having a small visual bug when i'm in the gui of AA crates, when i'm near a smeltery with Fuel input machine in it.

I've talked with the mod author, and done some tests, in my first test i tought it was from TinkerConstruct but with more test it appears it could come from TinkerI/O.

You can see our discussion here, i've made a video showing whats it doing on the second topic:

https://github.com/Ellpeck/ActuallyAdditions/issues/177

https://github.com/SlimeKnights/TinkersConstruct/issues/2272

**Comment by gkbm2013** [comment]
I released a new version for Tinker I/O, but I didn't fix the bug. I think I need more time to fix it. 
Sorry...

*Edit
I also need more time to find out whether the bug was caused by Tinker I/O...

**Comment by gkbm2013** [comment]
Hi!
I tested the related mods in my computer, however, I can't find the bug you said.
Here is the video I made.
https://drive.google.com/file/d/0B3Uwi7RD-jxXekpGRkUyLUNTV0E/view

**Comment by Gayanfalor** [comment]
Hmm that strange, as i could see in the video you are not looking too long into the crate, sometime the bug apearing almost instantly, sometime you need to look the crate about 10-20 sec.

Also in my fuel input machine we had some charcoal as we have not made some fuels already.

Btw i was using forge-1.10.2-12.18.1.2027-universal
tinker_io-1.10-release 2.3.1c
ActuallyAdditions-1.10.2-r56
Waila-1.7.0-B3_1.9.4
TConstruct-1.10-2.3.3a

I talk about Waila because in the server console i get many messages talking about waila and many other mods:

`[18:41:59] [Netty Server IO #2/WARN] [Waila/]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:104
[18:41:59] [Netty Server IO #2/WARN] [Waila/]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
[18:41:59] [Netty Server IO #2/WARN] [Waila/]: Catched unhandled exception : [class forestry.arboriculture.tiles.TileSapling] java.lang.NullPointerException
[18:42:22] [Netty Server IO #2/WARN] [Waila/]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:104
[18:42:22] [Netty Server IO #2/WARN] [Waila/]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
[18:42:22] [Netty Server IO #2/WARN] [Waila/]: Catched unhandled exception : [class slimeknights.tconstruct.tools.tileentity.TileCraftingStation] java.lang.NullPointerException`

If you cant recreate the problem, i dunno from what it could come :'(
EDIT: I'll still test with the new mod version and see it i still get the bug

**Comment by gkbm2013** [comment]
I looked the crate for 1 minute, I still can't find any problem. I think you should test in a new map and test these mod again. The bug may be caused by another mods.
You can also send the map you played to me,if you are willing to.

**Comment by Gayanfalor** [comment]
Yeah i tried a new map in creative solo with smeltery and crates its not bugging its strange, i can send you the map but i dont know if it will work if you dont have all the mods

EDIT: here is the zip with the map in it   https://drive.google.com/open?id=0B9iNaLFrsdUpSEc1dlF1MjFHS1U

**Comment by gkbm2013** [comment]
I think there are another blocks in that chunk cause the bug...

**Comment by Gayanfalor** [comment]
Yeah it seems so, sorry for that then.

Did you tried the map ? i ask if i can remove it from the drive ^^.

Thanks for your help then :)

**Comment by gkbm2013** [comment]
I can't find the map...
Can you send the map by a email?
gkbm2013@gmail.com

**Comment by Gayanfalor** [comment]
the map is called test2.zip is the drive link not working ?

Edit i tried to send you by mail but they said me file over 25Mo should be shared with drive

**Comment by gkbm2013** [comment]
I tested the map with following mods.
ActuallyAdditions-1.10.2-r56
EnderIO-1.10.2-3.0.1.73_beta
jei_1.10.2-3.7.3.221
Substratum-1.10.2-1.6.0.1
TConstruct-1.10-2.3.3a
tinker_io-1.10.2-release 2.3.3
Waila-1.7.0-B3_1.9.4

I still can't find the bug.

I think you can remove all the mods you installed on by one for test.

**Comment by C0rn3j** [comment]
This is apparently not a TInkerIO bug but a Tconstruct bug, now you can sleep easily ^^
https://github.com/SlimeKnights/TinkersConstruct/issues/2316

**Comment by Gayanfalor** [comment]
Ah its nice you have spotted from what its coming :)
