### ISSUE TITLE
Does Tinker i/o have integration with JEI?

### ISSUE THREAD

**Issue by TheRoyalReaper** [gkbm2013/tinker-IO#23]
since TiCon does not come with base metals like aluminum you can't craft the solid fuel, if there's no integration is there a way to find the recipes?

**Comment by gkbm2013** [comment]
I will change the recipe in a new version. Thanks for the report.

**Comment by gkbm2013** [comment]
The last version had fixed the bug!
https://github.com/gkbm2013/tinker-IO/commit/9f562a8d00b814dc32e47dd000377a90d0e16300
