### ISSUE TITLE
smart output doubling some modded ores

### ISSUE THREAD

**Issue by Tsukiumy** [gkbm2013/tinker-IO#24]
for some odd reason the smart output is doubling ores when it shoudn't like it
http://imgur.com/a/D1rEs
some images to explain the bug, vanilla ores are OK, but the modded no.
forge 12.18.1.2050
TConstruct-1.10.2-2.4.0.jenkins312
Tinker I/O beta 2.3.4

**Comment by gkbm2013** [comment]
I will fix the bug as fast as I can. Thanks for your report.

**Comment by gkbm2013** [comment]
I tested in my computer, but I can't find any bug when I used smart output to cast a cobalt ingot.

**Comment by Tsukiumy** [comment]
hmm, strange, i will get another instance and put only some mods that i can think that can be causing this weird interaction and report back after i test some more.

**Comment by Tsukiumy** [comment]
so, i tested all mods that could be causing any oregen or that could interact in some form with the ores(processing), and coudnt find the culprit, so i will close this issue, and if a find the culprit i reopen and report on the tracker from that one to find the why this weird interaction.

**Comment by Tsukiumy** [comment]
after some more testing i found the culprit, reopening there to see if it can help figure out the why this could be happening
cross post
https://github.com/xLionel775/AgriculturalExpansion/issues/17

**Comment by gkbm2013** [comment]
Did you place any block or plant with smart output in the same chunk ?

**Comment by Tsukiumy** [comment]
i created a new instance with just the tinkers and the agricultural expansion, built the smeltery and put the ingot inside the smeltery to test and it still doubled the output, i just cant do more tests and prints for a while as my note just gone for repair and i will need a few weeks till i get it back.
