### ISSUE TITLE
Fuel Input Machine Causing Lag

### ISSUE THREAD

**Issue by TonRZN** [gkbm2013/tinker-IO#25]
After checking what was causing the lag I've noticed that the smeltery causes 6 chunk updates, but when I add the Fuel Input Machine the chunk updates rise to 20+ and causes a lot of lag 
Edit:  Also the Fuel Input Machine drop nothing when broken (not even itself )
Another Edit: I'm using the latest version of the mod.

**Comment by TonRZN** [comment]
Sorry for the typo

**Comment by the-creamster** [comment]
I can confirm this to be happening aswell; getting a fps drops of 60-80.

**Comment by gkbm2013** [comment]
I had fixed the bugs. Thanks for your report!
https://github.com/gkbm2013/tinker-IO/commit/9f562a8d00b814dc32e47dd000377a90d0e16300
