### ISSUE TITLE
WARN because of missing sounds

### ISSUE THREAD

**Issue by C0rn3j** [gkbm2013/tinker-IO#26]
Relevant part: http://pastebin.com/r1cSwkqT

Full log: http://pastebin.com/NXdsNnLy (the crash is irrelevant)

Forge 2088

TConstruct had a partial rewrite of something, maybe that's the problem?

**Comment by gkbm2013** [comment]
The warning will not affect the sound of Tinker I/O and TConstruct. But I will try to fix it. Thanks for report.
