### ISSUE TITLE
[Bug] Multiple Crashes with new Tinkers

### ISSUE THREAD

**Issue by MysticAura** [gkbm2013/tinker-IO#28]
MC Version: 1.10.2
Forge Version: 2086
Tinkers Version: 251
Tinker I/O Version: 235

This crash occurs when loading up a world with the fuel input on the smeltery. It was an auto crash on placement as well, when the smeltery tried to reform.
[Crash Log](http://pastebin.com/u5khridr)

I can not downgrade Tinkers version because the current Immersive Engineering requires it.

Another crash caused by trying to access the gui on the smart-output.
[Crash Log 2](http://pastebin.com/CctibLtN)

**Comment by Gayanfalor** [comment]
Hello i got the same crash just placed the fuel input server insta crashed and cant restart, i had to restore a fresh backup ^^

EDIT: nevermind, i was still using the tinker io ver 2.3.3 and i have not tested yet with the latest (2.3.5)

**Comment by Hypsellis** [comment]
I got another crash too http://pastebin.com/RkYpYs3e

**Comment by Gayanfalor** [comment]
Hello,

i dunno if this error coming from tinker-io in the construct thing i've seen taiga errored before tinker io (  UCE taiga{${version}} [Tinkers Alloying Addon](taiga-1.10.2-1.1.3.jar)). try disabling taiga and see if it comes from it.

Btw i'm a mod user too so i can be wrong and mod author or other guys can know more about this.

It could help too to update your java like you have java8 1.8.0.25 and the latest one is 1.8.0.102.

Ps: Do you have fps loss too ? i have a moddpack in 1.10.2 too but i think its too  much or i dont know but my fps goes really low very often

**Comment by gkbm2013** [comment]
I will check if the bug cause by Tinker I/O or not. Thanks for report.
