### ISSUE TITLE
[Feature] Seared Stone

### ISSUE THREAD

**Issue by thejims** [gkbm2013/tinker-IO#29]
Smart Output allows Casting Basin in it to cast Glass, however, it does not work with Seared Stone?

**Comment by gkbm2013** [comment]
I will add a upgrade for smart output to provide basin mode. Thanks for suggestion!

**Comment by gkbm2013** [comment]
HI! I had added the basin casting mode for Smart Output. Thanks for your suggestion again!
https://minecraft.curseforge.com/projects/tinker-i-o/files/2349757
