### ISSUE TITLE
Is there a trick to get conduit/hopper/pipes to insert fuel?

### ISSUE THREAD

**Issue by tgstyle** [gkbm2013/tinker-IO#31]
1.10.2 version 2.4.1

I have tried front, sides, back, top, bottom. The fuel input machine will not take any input except manually.

Is it supposed to be that way?

**Comment by BrewingCoder** [comment]
I can verify this; there's no way to pipe in fuel via hopper, item conduits, or AE2 interface

**Comment by gkbm2013** [comment]
It's a bug... I will fix it as fast as I can. Thanks for report!

**Comment by gkbm2013** [comment]
I fixed the bug. Thanks for report again!

The fixed version will release in Tinker I/O pre-release 2.4.2.
