### ISSUE TITLE
Hitting Fuel Input w/hammer rotates block but removes/deletes all upgrades

### ISSUE THREAD

**Issue by BrewingCoder** [gkbm2013/tinker-IO#33]
put Fuel input into smeltery, load w/fuel and upgrades.

accidentally (or on purpose) hit the block with a wrench or hammer.  I happened to click w/the Immersive engineering hammer.

the block rotates.

when this happens it basically resets the block losing any inventory such as upgrades and fuel.

**Comment by gkbm2013** [comment]
I will fix it in the next version. Thanks for report!

**Comment by gkbm2013** [comment]
I close the block rotation function of Tinker I/O's block. Thanks for report again!

The fixed version will release in Tinker I/O pre-release 2.4.2.
