### ISSUE TITLE
Smart Output with EnderIO Conduits

### ISSUE THREAD

**Issue by tgstyle** [gkbm2013/tinker-IO#34]
1.10.2 version 2.4.1

Not sure what is the culprit here, but if you have an ingot cast in the Smart Output and use EnderIO Item conduits for extraction, it causes really high CPU utilization, and is compounded by using more Smart Outputs with an ingot cast. Basin casting works fine. The work around I have had to do is use a hopper for extraction in to a chest where I can use Item conduit. Limiting the Smart Outputs function for casting ingots.

**Comment by gkbm2013** [comment]
I can't find the bug during test in my computer. But I change some code about packet sending for Smart Output. Hoping this can fix the bug.
The fixed version will release in Tinker I/O pre-release 2.4.2.
Thanks for report!
