### ISSUE TITLE
Fuel Input Won't Work

### ISSUE THREAD

**Issue by austin-wiechman** [gkbm2013/tinker-IO#36]
I am on version 2.4.3 for 1.10, and the fuel input doesn't seem to be communicating properly with the smeltery controller. The fuel input will say the temperature is at 1000 or more whereas the controller will say it is as 0. Any idea why this is, or how to fix it?

**Comment by gkbm2013** [comment]
Could you provide the forge version and mods you installed?

**Comment by austin-wiechman** [comment]
Forge 12.18.3.2254, the latest version. As for mods, there are a lot. You can find most of them [here](https://minecraft.curseforge.com/projects/acemc-1-10-modpack/relations/dependencies), besides that, there are Mekanism and BetterPvP.

**Comment by gkbm2013** [comment]
Actually Fuel Input Machine work fine in my computer, so I don't know how to fix it...
Sorry.
