### ISSUE TITLE
Space in filename

### ISSUE THREAD

**Issue by C0rn3j** [gkbm2013/tinker-IO#37]
Hi, this mod is one of the few that have a space in the filename, would you consider replacing it with an underscore? Thanks!

http://i.imgur.com/A4KSJQI.png

It breaks my program, which I'm planning to fix, but I think it'd be better if mods had consistent naming too ^^

**Comment by gkbm2013** [comment]
Thanks for suggestion. But recently, I think I will not change the filename.
