### ISSUE TITLE
Some Ores can be used in ore crusher some cant

### ISSUE THREAD

**Issue by tyler489** [gkbm2013/tinker-IO#38]
Confused as how your ore crusher decides if it works with that ore. i made an ore chunk with Exnihilo for a custom ore and it works fine with your ore crusher (suprisingly) but copper also from exnihilo wont process inside.. iridium from themal expansion wont but mana infused will please help .,

**Comment by gkbm2013** [comment]
Ore Crusher determine whether the ore can crush or not by Ore Dictionary. So check the ore you put into Ore Crusher had been registered in Ore Dictionary.

The ore which Ore Crusher does not support is registered in https://github.com/gkbm2013/tinker-IO/blob/1.10.2-GKB/src/java/tinker_io/registry/OreCrusherBanLiatRegistry.java
Hoping this can help you.

**Comment by tyler489** [comment]
Huh copper wont process and it is definitly ore dictionaryed

**Comment by gkbm2013** [comment]
Thanks for report! I will fix the problem!

**Comment by gkbm2013** [comment]
Sorry, it's seems that Ex Nihilo didn't register the item into Ore Dictionary.
