### ISSUE TITLE
EnderIO conduits inserting to Ore Crusher

### ISSUE THREAD

**Issue by mcsoapthgr8** [gkbm2013/tinker-IO#39]
I am using EnderIO item conduits set on In/Out mode to insert into the Ore Crusher. The ore is being inserted into both the input and output sides of the machine, when I would expect that it should only go into the input side.

I have the Ore Crusher set up with 64 speed upgrades, a Fortune upgrade, and 2 Fortune 3 books for the full ore tripling.

I'm using the [HyperAntix](https://mods.curse.com/modpacks/minecraft/252898-hyperantix) 1.10.2 modpack. This pack hasn't been updated for a little while, so I realize that this issue may have already been fixed.

![2017-04-21_17 59 44](https://cloud.githubusercontent.com/assets/16899874/25297530/613a46b6-26bc-11e7-92bd-8230e4772cb6.png)

**Comment by mcsoapthgr8** [comment]
I did some additional testing and found that this issue only happens when the item conduit is inserting from the bottom of the machine. If the item conduit is pointing in from the sides, the ores only go into the input slot.

**Comment by gkbm2013** [comment]
By default, Ore Crusher can input item in any side except bottom. I will change the rule to support some mods which can I/O in the same side.
Thanks for report!

**Comment by gkbm2013** [comment]
The problem had fixed in release 2.4.4. https://github.com/gkbm2013/tinker-IO/commit/2e548034725112397afe08f8737bb89bf87013d8

**Comment by mcsoapthgr8** [comment]
Thank you!
