### ISSUE TITLE
New Fuel recipe

### ISSUE THREAD

**Issue by blockbreaker1361** [gkbm2013/tinker-IO#4]
The iron ingot in the fuel recipe doesn't make much sense. I would use, in a shapeless recipe, one glowstone dust, one redstone dust, one gunpowder and one coal/charcoal and receive 4 fuel as a result. I really like your mod and hope that you give my suggestion some consideration. Thank you and have a nice day. :)

**Comment by Staegrin** [comment]
It's actually an aluminium ingot or dust.
