### ISSUE TITLE
Cannot remove items from Smart Output using EnderIO item conduits or ExtraUtils2 transfer nodes

### ISSUE THREAD

**Issue by mcsoapthgr8** [gkbm2013/tinker-IO#40]
I have attached EnderIO item conduits and ExtraUtils2 transfer nodes to the bottom and sides of the SmartOutput - items in the output side are not removed.

Since those did not work, I used a hopper instead.

I'm using the [HyperAntix](https://mods.curse.com/modpacks/minecraft/252898-hyperantix) 1.10.2 modpack. This pack is using v 2.4.1. I'm not sure if this has been updated in 2.4.3.

**Comment by gkbm2013** [comment]
The problem had been fixed in release 2.4.4. https://github.com/gkbm2013/tinker-IO/commit/2e548034725112397afe08f8737bb89bf87013d8

**Comment by mcsoapthgr8** [comment]
Thank you!
