### ISSUE TITLE
Can't Stop The Server

### ISSUE THREAD

**Issue by ghost** [gkbm2013/tinker-IO#41]
https://github.com/SlimeKnights/TinkersConstruct/issues/2929
used forge 2304 everything latest

**Comment by gkbm2013** [comment]
Thanks for report! I will fix the problem.

**Comment by gkbm2013** [comment]
The bug has been solved in **tinker_io-1.11.2-alpha 2.5.1c**
Thanks for report!

**Comment by ghost** [comment]
thanks
