### ISSUE TITLE
2.5.0d crashes dedicated server Forge 1.11.2 build 2304

### ISSUE THREAD

**Issue by kreezxil** [gkbm2013/tinker-IO#42]
tinker_io{alpha 2.5.0c} [Tinker I/O] (tinker_io-1.11.2-alpha 2.5.0d.jar) crashes dedicated server Forge 1.11.2 build 2304

Notes:
     on startup
     *I find it interesting that internally the mod version is 2.5.0c yet the file name version indicates it should be higher.

crash report:
https://gist.github.com/7e84143512448e2d0dbbd9b2b5ba310d

fml server latest:
https://gist.github.com/00474f1d2ca311b5282718c92e021d8e

**Comment by Wizardon777** [comment]
Crashing my server as well...
Please help...

[crash-2017-05-29_00.10.03-server.txt](https://github.com/gkbm2013/tinker-IO/files/1035827/crash-2017-05-29_00.10.03-server.txt)

**Comment by gkbm2013** [comment]
Thanks for report. I will fix it!

**Comment by gkbm2013** [comment]
The bug has been solved in **tinker_io-1.11.2-alpha 2.5.1c**
Thanks for report!
