### ISSUE TITLE
[110.2] JEI error?

### ISSUE THREAD

**Issue by Claycorp** [gkbm2013/tinker-IO#43]
https://pastebin.com/QNCgBXDZ
You get this every time on startup.

**Comment by gkbm2013** [comment]
Plugin for JEI is developing. I will fix the bug as fast as I can. Thanks for report!

**Comment by gkbm2013** [comment]
The bug has been solved in **tinker_io-1.11.2-alpha 2.5.1c**
Thanks for report!

**Comment by MJRLegends** [comment]
@gkbm2013 Any chance of a 1.10.2 fix for this :D

**Comment by gkbm2013** [comment]
@MJRLegends Okay~ I will try to fix it!

**Comment by gkbm2013** [comment]
The bug has been solved in **tinker_io-1.10.2-2.4.4a**
Thanks for report again!

**Comment by MJRLegends** [comment]
@gkbm2013 Thank you :D
