### ISSUE TITLE
Ore crusher does not break when mined by any pickaxe

### ISSUE THREAD

**Issue by Drake07** [gkbm2013/tinker-IO#44]
Server prints this [error](https://pastebin.com/viC7ux7W) when i try to break it.

**Comment by gkbm2013** [comment]
Could you tell me the version of Tinker I/O?

**Comment by Drake07** [comment]
release 2.5.1d

**Comment by gkbm2013** [comment]
I fixed the bug in Tinker I/O release 1.11.2 2.5.2c. Thanks for report!
