### ISSUE TITLE
Crash on loading modpack 5/7

### ISSUE THREAD

**Issue by turnerlewis** [gkbm2013/tinker-IO#45]
Load up my modpack and crash. Here is the crash report;

[crash-2017-07-26_03.11.24-client.txt](https://github.com/gkbm2013/tinker-IO/files/1175259/crash-2017-07-26_03.11.24-client.txt)

**Comment by gkbm2013** [comment]
I fixed the bug in Tinker I/O **1.11.2 2.5.2d**.
Thanks for report.
