### ISSUE TITLE
[1.12] Wrong Flux API

### ISSUE THREAD

**Issue by TheLimePixel** [gkbm2013/tinker-IO#46]
The 1.12 version crashes because you're using the old Redstone Flux API.

 https://pastebin.com/1pPcBJ8M

**Comment by Furuchiru** [comment]
I have the same crash
https://pastebin.com/tt6wnUTC

**Comment by gkbm2013** [comment]
The bug will be solved in **tinker_io-1.12-beta 2.5.3f**

Before I change the energy system from RF to Forge Energy, we need to install [Redstone Flux](https://minecraft.curseforge.com/projects/redstone-flux) to provide the energy interface for "Ore Crusher " and "Stirling Engine".

Thanks for reporting!
