### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by Shindur** [gkbm2013/tinker-IO#47]
So, not sure if this is Tinker I/O or actual Tinkers' Construct... I created my own modpack, and decided I wanted to make it a server for me and my friends. Well, I ran the server on my local machine and it loaded up fine, but when I go to connect to the server I get kicked with an error message saying:
Internal Exception: java.lang.IllegalStateException: Could not determine owner for the override on tinker_io:blockpuremetal. Value: Block(null).

Thanks for looking at this, and let me know if it's something that needs to be reported to Tinkers' devs :)

**Comment by gkbm2013** [comment]
Could you provide the log files of your server? I need more information to solve the bug. Thanks!

**Comment by Shindur** [comment]
Which log would you need me to provide? the fml-server-latest.log, fml-server-1.log, latest.log, or fml-junk-earlystartup.log? These are the only files I see in the server's log folder.

**Comment by gkbm2013** [comment]
I need the log which was generated when the Exception occurred.

**Comment by Shindur** [comment]
https://www.dropbox.com/sh/8a8xb5myyzu7r4k/AADRbDVVHiBlH2VMvXgC1ZAQa?dl=0
I don't have a pro pastebin account to copy the log files, however I did upload them to the dropbox link above. There's the fml-client-latest log and the fml-server-latest log file. I searched through and couldn't find where the exception would occur however. Picture below shows the error when connecting.
![stuffandthings](https://user-images.githubusercontent.com/20944228/28905000-9356d0b2-77dc-11e7-8db4-b1d0f98c6372.png)

**Comment by Shindur** [comment]
Can confirm this is a tinker I/O issue, i just disabled it in my profile and removed it from the server mods, and I was able to connect.

**Comment by gkbm2013** [comment]
Did you put **blockPureMetal** (Liquid type of Curshed Ore) into your inventory?

**Comment by Shindur** [comment]
It was a fresh start of the server, fresh world.
