### ISSUE TITLE
1.12-2.5.3f cannot push/pull items with item ducts

### ISSUE THREAD

**Issue by tgstyle** [gkbm2013/tinker-IO#48]
Pulling from smart output with item ducts does not work.
Pushing Solid Fuel to fuel input machines does not work. Hoppers do not work for this either.

**Comment by gkbm2013** [comment]
Could you give me the mods list and forge version you installed? The function of push and pull items work fine in my computer.

**Comment by tgstyle** [comment]
https://gist.github.com/tgstyle/c1089389c20d0463c476e898c7c199db

**Comment by ghost** [comment]
If it helps, I've reproduced this issue with the FTB Unstable pack, with your mod added.

**Comment by gkbm2013** [comment]
Actually I forgot to register the burn time of Solid Fuel, so it was not accepted by Fuel Input Machine...
The bug was fixed. Thanks for your report!
