### ISSUE TITLE
[1.7.10 release 1.5.0] Input Machine isn't part of the smeltery.

### ISSUE THREAD

**Issue by Mohl97** [gkbm2013/tinker-IO#54]
Pretty much, the input machine only works if it's directly adjacent to the Smeltery Controller. Which means that if it's anywhere but next to one of the edges of the smeltery, it makes the smeltery unusable, due to not counting as a smeltery block.

Because of this, my only way of using the thing is to just slap it directly in front of the controller, removing any ability to input ores.

I'm not sure if this has been fixed in the later versions, but given that my pack's stuck on 1.7.10 for the foreseeable future, this is kind of all I'm left with.

**Comment by gkbm2013** [comment]
Because of the technical problem, we don't know how to register Fuel Input Machine as a part of Smeltery in Minecraft 1.7.10. I am sorry about that...
