### ISSUE TITLE
 tinker_io-1.11.2-release 2.5.5c dependency issue

### ISSUE THREAD

**Issue by kreezxil** [gkbm2013/tinker-IO#55]
It depends on redstone flux api, the only available redstone flux api is tagged for 1.12 and refuses to run under 1.11.2.

**Comment by gkbm2013** [comment]
Is the problem still exist?

**Comment by kreezxil** [comment]
I haven't checked since I made this report. Did you release a patch to **fix** the issue. If so I'll check today and get back to you.

**Comment by Vertitt** [comment]
Hi. I was creating a new modpack when i noticed that redstone flux api is downloaded with tinker io on 1.10.2 which created crash.
