### ISSUE TITLE
[Suggestion] Option to disable and remove the Ore Crusher and Crushed Ores

### ISSUE THREAD

**Issue by D3nnis3n** [gkbm2013/tinker-IO#56]
Hey, as your mod allows very easy ore tripling which is more difficult in Mekanism which we use as main mod, we'd like to disable that Feature, but can't.

**Comment by gkbm2013** [comment]
Maybe you could ban the recipe of Ore Crusher to prevent user from using it.

**Comment by D3nnis3n** [comment]
Yeh, i'm doing this at the Moment, but it would be much better if all those items wouldn't be generated first. Sorry for my late Response.
