### ISSUE TITLE
Major dupe bug

### ISSUE THREAD

**Issue by ShadowXx** [gkbm2013/tinker-IO#6]
Put a single nugget into a smeltery with a fuel input machine attached to speed up the process, This creates 16Mb of molten metal.

Pour the 16MB into a Smart output machine with an ingot cast, The machine seems to ignore the amount and still produce an ingot.

After further testing, 16MB in a tank (regardless of type, BC tanks were used in this example), Then Steves factory manager to move 1mb every 5 seconds into the smart output machine, still produces an ingot. Meaning every ingot can produce 144 ingots, further increasing to ridiculous amounts.

If needed i can take screenshots of the setup including steves factory manager program, however i dont think its needed. TinkerIO doesnt seem to be requesting the set amount per ingot.

**Comment by gkbm2013** [comment]
I have fixed the bug~ Thanks for your report!
