### ISSUE TITLE
Support for ItemHandler capability in smart output

### ISSUE THREAD

**Issue by CplPibald** [gkbm2013/tinker-IO#60]
Are there any plans to support the IItemHandler capability for the Smart Output?

I'm having trouble extracting from a SO into a pipe system like Integrated Tunnels which use the newer (as of 1.10, I think) Forge Capabilities system instead of the older ISidedInventory.

Right now the workaround I'm using is to put a hopper under the SO to eject into a chest, and then extract from that chest.  But the hopper is not nearly fast enough to keep up with a smart output.

Another solution that would fix this is to have the SO auto-eject items into an adjacent inventory, but I don't know if you'd be willing to do that since it would sidestep the extremely expensive slot upgrades for the SO.

**Comment by WeaselOnaStick** [comment]
Only way i could just EXTRACT items from SO is **hoppers**

**Comment by gkbm2013** [comment]
Sorry for missing the issue. Because I am busy in my real life now, I think I will fix the bug till February.

**Comment by gkbm2013** [comment]
IItemHandler have been added in Tinker I/O release 2.6.0.
Thanks for report!

**Comment by iridiumlynx** [comment]
Still cannot pipe items out of the Smart Output in Tinker I/O 2.6.1
