### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Azuxul** [gkbm2013/tinker-IO#61]
Hi,

My server crash due to a NPE of tinker-IO.

Tinker-IO version : 2.5.6e
Forge version : 14.23.1.2565

Crash report : 
[crash-2018-01-05_22.36.00-server.txt](https://github.com/gkbm2013/tinker-IO/files/1608009/crash-2018-01-05_22.36.00-server.txt)

**Comment by gkbm2013** [comment]
The problem have been solved in Tinker I/O release 2.6.0.
Thanks for report!
