### ISSUE TITLE
So the hopper is the only thing that can extract from the smart output?

### ISSUE THREAD

**Issue by KalaMiDeviL** [gkbm2013/tinker-IO#63]
I've tried extra utilities 2, TE, stupid BC 7 pipes and even the fucking BC chute! Y U NO WORK? And I did connect them on the bottom side, by the way.
The only thing that can handle it, is the almighty XNet, but that means I gotta pluck an XNet controller on there and it's just so out of place.
My ore processing is supposed to be perfect, so don't trigger my OCD with random incompatibility!
Anyway, loved your mod ever since TCon went crazy with its multi-block boundaries - but fix it, please!

**Comment by gkbm2013** [comment]
Please refer to #60.
