### ISSUE TITLE
Server Crash placing smart output

### ISSUE THREAD

**Issue by BrewingCoder** [gkbm2013/tinker-IO#65]
Server Crash when placing a smart output block under some TE FluidDucts already filled with molten liquid (From I/O's crushed ore, not vanilla or tico liquid).  So the fluid pipe is primed and ready to insert liquids as soon as block appears.  I was basically swapping out a full portable tank for smart output block :)

Crash log enclosed.

[crash-2018-01-24_17.24.54-server.txt](https://github.com/gkbm2013/tinker-IO/files/1661905/crash-2018-01-24_17.24.54-server.txt)

**Comment by gkbm2013** [comment]
The bug was solved!
Thanks for the report!
