### ISSUE TITLE
Cannot pipe items out of the Smart Output

### ISSUE THREAD

**Issue by McBaconator5000** [gkbm2013/tinker-IO#66]
Playing: Modern Skyblock 2 Version 2.9.0.1 forge version 14 23.1.2590

Steps to reproduce: Place liquid in smart input. Place ingot-cast in smart input. Have ingot be made. Have no way of getting ingot out except for opening the gui and taking it out by hand.

Edit: a hopper works. All other modded methods, including Extra Utilities transfer node and retrieval nodes, and Actually Additions ESD fails. They read the Smart Output as having no inventory

**Comment by gkbm2013** [comment]
The problem had been solved in Tinker I/O release 2.6.0a. Please refer to #60.

**Comment by cybercronx** [comment]
I am actually running into this issue right now. I cant pull anything out of it unless its a regular hopper.

Using version 2.6.1
