### ISSUE TITLE
Suggestion: Way to cast blocks with tinker io

### ISSUE THREAD

**Issue by Staegrin** [gkbm2013/tinker-IO#7]
Currently there is no way to cast blocks with tinker io. 

I would suggest placing a casting basin into the cast slot to allow the smart output to cast blocks.

**Comment by gkbm2013** [comment]
Okay, I will add this function into next version!

**Comment by Staegrin** [comment]
While we can now cast glass with the smart output, could it be made to include the metals?

**Comment by gkbm2013** [comment]
Umm...I think ingot casting with smart output is fast enough...

**Comment by Staegrin** [comment]
Ok, just wanted to ask. Keep up the good work.
