### ISSUE TITLE
[1.12.2] Rendering Crash while Browsing JEI

### ISSUE THREAD

**Issue by Vyraal1** [gkbm2013/tinker-IO#70]
https://pastebin.com/jRePXE8P

**Comment by WonderDog** [comment]
Same crash with draconic ores rendering in JEI

Single Player - All the mods modpack

JEI version 4.8.5.147

Repeatable just look at the recipe for draconic ores and select the Tinker I/O tab

[Crash Log](https://pastebin.com/embed/4wCEMYVU)

**Comment by Yoosk** [comment]
Same error once more in All the mods 3, Multiplayer official server.

[Crash log](https://gist.github.com/adfd483646d0555184ec6dff190c400d)

**Comment by gkbm2013** [comment]
Thanks for the report. The bug has solved in the next version!

**Comment by gkbm2013** [comment]
The bug fixes in Tinker I/O release 2.6.1.
Thanks for the report!
