### ISSUE TITLE
[main/WARN]: Missing sound for event: tinker_io:record.lonesome_avenue

### ISSUE THREAD

**Issue by Guinaro** [gkbm2013/tinker-IO#71]
Going over my minecraft log file I encountered following warning.
[main/WARN]: Missing sound for event: tinker_io:record.lonesome_avenue

Important or not? Just mentioning it here just in case.

Guinaro

**Comment by gkbm2013** [comment]
This is the sound added in Minecraft 1.7.10. The file has been renamed. I just forget to delete the old one. Thanks for the report!
