### ISSUE TITLE
[1.12.2] Game Breaking Bug with Fuel Input and a hopper

### ISSUE THREAD

**Issue by TorinnTheDragon** [gkbm2013/tinker-IO#72]
So I just wanted to do was to keep on fueling the Input Machine, so I don't have to put it in manually and realized that the solid fuel is going into the upgrade slot as shown here, https://gyazo.com/c815475a7e15eba4c26cf1c5d2fd2fa7.  So hopefully you all can take care of this bug in

**Comment by gkbm2013** [comment]
The bug was fixed in Tinker I/O release 2.6.1.
Thanks for the report!
