### ISSUE TITLE
Fast Hoppers and Item Ducts won't interact with Tinker I/O devices, Extra utilities crashes.

### ISSUE THREAD

**Issue by Yadokingu** [gkbm2013/tinker-IO#73]
The only thing that seems to work with Tinker I/O blocks are vanilla hoppers, which is a tad annoying, because it means you can't pull fast enough from a Smart Output.

Crash log and general log:
[2018-02-28-3.log](https://github.com/gkbm2013/tinker-IO/files/1768067/2018-02-28-3.log)
[crash-2018-02-28_17.49.46-server.txt](https://github.com/gkbm2013/tinker-IO/files/1768068/crash-2018-02-28_17.49.46-server.txt)

**Comment by ThaDaVos** [comment]
When will this be fixed?

**Comment by brisingraerowing** [comment]
This is because the mod is not using the standard capability system for inventory handling, which is the only method that most other mods support. This is a pretty major compatibility failure on the dev's part.

**Comment by gkbm2013** [comment]
@dvdbot @Yadokingu @BrisingrAerowing It seems that I forgot to add IInventory back when I was implementing IItemHandler......

**Comment by gkbm2013** [comment]
Duplicate of #67
