### ISSUE TITLE
redstone flux api dependance on 1.10.2

### ISSUE THREAD

**Issue by Vertitt** [gkbm2013/tinker-IO#74]
Hi. I was creating a new modpack when i noticed that redstone flux api is downloaded with tinker io on 1.10.2 which created crash.

https://github.com/gkbm2013/tinker-IO/issues/55

**Comment by gkbm2013** [comment]
hmm... not knowing how to fix it... 
Now, I am rewriting Tinker I/O in Minecraft 1.12.2.
I will try to solve the bug after I finish the work.
