### ISSUE TITLE
Crash when breaking the Tinoer I/O Smart Output

### ISSUE THREAD

**Issue by Vyraal1** [gkbm2013/tinker-IO#77]
https://hastebin.com/igofeqeyib.sql

**Comment by gkbm2013** [comment]
I will use the new Forge Capability to rewrite it. Thanks for the report!
https://github.com/gkbm2013/tinker-IO/blob/1.12.2/src/java/tinker_io/gui/SOGui.java#L104

**Comment by gkbm2013** [comment]
The bug was fix in Tinker I/O rewrite version! Thanks for your report!
