### ISSUE TITLE
Tinker-IO + JEI = Crash when viewing recipes 2.6.1

### ISSUE THREAD

**Issue by darkshadow1809** [gkbm2013/tinker-IO#78]
Crash report:

https://pastebin.com/qM7N7Hwv

#70

**Comment by Entoarox** [comment]
Similar issue, different error log: https://paste.dimdev.org/imucubasan.mccrash

JEI and Pure Metal dont seem to get along *at all*....

**Comment by DaNeo61** [comment]
Similar issue with Ender IO 

https://github.com/SleepyTrousers/EnderIO/issues/4744

**Comment by tyler489** [comment]
thats where this came from enderio 4744

**Comment by corgiblu** [comment]
I'm having this issue too. 
https://paste.ee/p/b2fAp

**Comment by Pythonic-Rainbow** [comment]
Seems that this is fixed in Rewrite 2.7a

**Comment by gkbm2013** [comment]
The problem was solved in Tinker I/O rewrite version! Thanks for your report!
