### ISSUE TITLE
when tinker-IO running on the SpongeForge Server cause some errors

### ISSUE THREAD

**Issue by MoeShimaKaze** [gkbm2013/tinker-IO#79]
Error logs:https://pastebin.com/vKtU4tSs
Forge Version:1.12.2-14.23.4.2705
SpongeForge Version:1.12.2-2705-7.1.0-BETA-3291
Mod list:https://pastebin.com/Zsf5A1wL
Plugins List:https://pastebin.com/bfLvYCpr
Tinkers Construct Version:TConstruct-1.12.2-2.10.1.87
Tinkers-IO Version:2.6.1

**Comment by gkbm2013** [comment]
The implementation of ItemStackHandler in Tinker I/O is wrong. I am rewriting the mod, and hopefully I will resolve the problem in the end of August. Thanks for the report!

**Comment by gkbm2013** [comment]
The problem was fix in Tinker I/O rewrite version! Thanks for your report!
