### ISSUE TITLE
[Feature Request] Alloy Controller Block

### ISSUE THREAD

**Issue by SnowShock35** [gkbm2013/tinker-IO#8]
Hi,

I wanted to suggest a neat idea I had for Tinker IO. So here it is...

New Features:
Config Option: (Boolean) Disable alloy creation in smeltery.
New Block: Alloy Controller - Used to enable/disable (Depending on cfg option above) and control the different alloys made within the smeltery and what fluids mix with other fluids. 

Hope you like the idea. Thought about making this a separate mod but I'm a java beginner coder and this mod would IMO suit it very well.
-Snow ;)

**Comment by gkbm2013** [comment]
Tinker I/O will add a Alloy Separator in the feature version ! Thanks for your suggestion !
