### ISSUE TITLE
Tinker-IO Pure Metal Crash

### ISSUE THREAD

**Issue by Toby406** [gkbm2013/tinker-IO#80]
Everytime i check the uses for cobblestone with JEI, my game crashes: https://paste.dimdev.org/tatuzuyowa.mccrash
Maybe #70 ?

**Comment by tyler489** [comment]
This is because tinkerio says it registers its fluid to a block. Then when enderio tries to get the block form it returns undefined.

**Comment by Toby406** [comment]
So gkbm2013 is busy currently, could the Enderio dev fix that? I don't want to write an issue about something, that isn't his fault...

**Comment by gkbm2013** [comment]
hmm... I am still rewriting Tinker I/O, and hopefully I will resolve the problem in the end of August.

**Comment by remclave** [comment]
gkbm2013, Just reported this on the EnderIO github (#4833 [closed]) but it appears the issue is still ongoing.

**Comment by gkbm2013** [comment]
The problem was solved in Tinker I/O rewrite version! Thanks you all for the discussion!
