### ISSUE TITLE
rw2.7.0 No Class Defined Error on Dedicated Server on Startup

### ISSUE THREAD

**Issue by kreezxil** [gkbm2013/tinker-IO#81]
Issue:  1.12.2-rw2.7.0 crashes dedicated server Forge 1.12.2 build 2757

Notes:
     No Class Defined Error

crash report:
https://gist.github.com/ef84b70a3705736bf4017c0cd6a5d616

fml server latest:
https://gist.github.com/babf4a3d67d2d02878e45487c5578887

**Comment by gkbm2013** [comment]
Thanks for your report! The bug is fix in rw 2.7.0a
