### ISSUE TITLE
There's anyway to make the smart output faster? 

### ISSUE THREAD

**Issue by Zazukih** [gkbm2013/tinker-IO#85]
I remember in older versions smart output was faster than now, there's anyway to make it faster? It would be nice if you add a config to edit the speed.

**Comment by KenyMylankca** [comment]
yeah, i agree this. it's very very slower now. please add config to make it slower or add some upgrade like things...

**Comment by gkbm2013** [comment]
Yes... I slow down the speed of Smart Output. 😂
But I will add a config to control the speed of Smart Output.

**Comment by gkbm2013** [comment]
The feature was added in Tinker I/O rw 2.7.1.
Thanks for your suggestion!
