### ISSUE TITLE
Smart Output causing tps lag when liquids are left in its tank

### ISSUE THREAD

**Issue by alyip98** [gkbm2013/tinker-IO#86]
I believe that the problem is due to SORecipeChecker rebuilding a list of recipes from all registered casting recipes every tick. I'm not sure if this is addressed in the rw version, but if not, could you cache the recipes?

**Comment by gkbm2013** [comment]
Could provide the version of Tinker I/O ? Thanks!

**Comment by alyip98** [comment]
tinker_io-1.12.2-release 2.6.1, playing Enigmatica 2 Expert

**Comment by alyip98** [comment]
From tinker-IO/src/main/java/tinker_io/tileentity/TileEntitySmartOutput.java:
```
    private void updateRecipe() {
        ItemStack cast = inventory.getStackInSlot(ContainerSmartOutput.PATTERN);
        FluidStack fluidStack = tank.getFluid();
        if(currentMode == MODE_BASIN) {
            currentRecipe = SmartOutputRecipeHandler.findBasinCastingRecipe(cast, fluidStack);
        } else if(currentMode == MODE_CAST) {
            currentRecipe = SmartOutputRecipeHandler.findTableCastingRecipe(cast, fluidStack);
        }
    }
```
I suggest storing currentRecipe locally and only calling findBasinCastingRecipe when the fluid type has changed

**Comment by gkbm2013** [comment]
The code you found is in the RW version. And `findBasinCastingRecipe()` will be called only if `private boolean isChanged()` return true.

 - https://github.com/gkbm2013/tinker-IO/blob/1.12.2_rewrite/src/main/java/tinker_io/tileentity/TileEntitySmartOutput.java#L83
 - https://github.com/gkbm2013/tinker-IO/blob/1.12.2_rewrite/src/main/java/tinker_io/tileentity/TileEntitySmartOutput.java#L156
