### ISSUE TITLE
Lot of Insane ticking on the server with Smart Output.

### ISSUE THREAD

**Issue by StoneLegion** [gkbm2013/tinker-IO#88]
Not sure if it's the users setup and even then it should not cause this much lag. As you can see this is almost 15ms of lag.

https://i.imgur.com/lsZOwQa.png

the Second I broke it and replaced it went down over 15ms so I can confirm was not a error in reporting it.

Could I repeat it again? Not sure honestly all I can tell you is they had a tiny bit of material inside about 1 ingot and some nuggets worth.

https://i.imgur.com/ACKSE74.png

**Comment by gkbm2013** [comment]
The performance issue was solved in the RW version of Tinker I/O!
