### ISSUE TITLE
Smart Output, Fuel Input Machine and Ore Crusher Insta-Break with Bare Hand

### ISSUE THREAD

**Issue by dumbomb** [gkbm2013/tinker-IO#89]
[![Image from Gyazo](https://i.gyazo.com/83778353026d036d8dd635bae620bf1b.gif)](https://gyazo.com/83778353026d036d8dd635bae620bf1b)

Modlist used for testing:
![Modlist](https://user-images.githubusercontent.com/45940352/51083891-8450a180-1775-11e9-8d5b-0114adaba514.png)

**Comment by 2iguys** [comment]
I have this issue, and on top of that the block itself doesn't drop, its basically treated like a creative break.

**Comment by 2iguys** [comment]
*Bump* in hopes that this gets looked at eventually

**Comment by gkbm2013** [comment]
Hello, this bug was solved in Tinker I/O rw2.8.0. Thanks for the report!
