### ISSUE TITLE
[Bug?] Ticking block entity

### ISSUE THREAD

**Issue by TripOptic** [gkbm2013/tinker-IO#9]
Hello sorry to push this issue upon you, but I put a cobble pan in the Smart Output then contuined to pour aluminum brass in then crash. I can no longer load the world(I have a backup).

 Here is a pastbin of crash because I don't want to flood this Issue post with the log.
(paste deletes in 1 week)
http://pastebin.com/EjU8CcK5

**Comment by gkbm2013** [comment]
Ok, I had fix it. And released the new version. Thanks for your report!
