### ISSUE TITLE
Smart Output Block and Thermal Dynamics Servos

### ISSUE THREAD

**Issue by ghost** [gkbm2013/tinker-IO#92]
Modpack: Crimson Skies V1.2.4.2
Mod: tinker_io-1.12.2-release 2.6.1
Java

I have a smeltery melting _sand_ into _Clear Glass_.  The _Molten Glass_ in the Smeltery is moved into the side of _Smart Output_ block using a basic _Servo_ and _hardened fluiduct_.   The _Smart Output_ block has a _Basin Upgrade_. This all works fine, the _Molten Glass_ is cast by the Smart Output block into _Clear Glass_.

However, I cannot get another _Servo_ and _Itemduct_ to extract the _Clear Glass_ to a chest/crate/etc.  I've tried attaching the _Servo_ to multiple sides of the Smart Output block with no results.  The _Servo_ is set to ignore Redstone signals, but I still cannot get the output from any side of the block.

![2019-02-01_14 09 17](https://user-images.githubusercontent.com/7958470/52152444-4683c200-262b-11e9-9599-0d5aa9fcf858.png)
![2019-02-01_14 09 20](https://user-images.githubusercontent.com/7958470/52152445-4683c200-262b-11e9-9443-b3a7d153f390.png)
![2019-02-01_14 09 24](https://user-images.githubusercontent.com/7958470/52152448-471c5880-262b-11e9-8be8-ea458d54d686.png)
![2019-02-01_14 09 14](https://user-images.githubusercontent.com/7958470/52152450-471c5880-262b-11e9-81bc-da68af5968ab.png)

What am I missing?

**Comment by gkbm2013** [comment]
The issue is caused by the old API used in Tinker I/O 2.6.1. The issue was solve in Tinker I/O 1.12.2 rw2.8.2. Thanks for your report.
