### ISSUE TITLE
Ore Crusher destroys ores with no output when using speed upgrade

### ISSUE THREAD

**Issue by Corosauce** [gkbm2013/tinker-IO#93]
When you add any number of speed upgrades to the ore crusher, and put in ore, it destroys the ore, and nothing happens afterwards, no output, no progress, just ores lost forever.

Works fine without speed upgrades.

If I put a stack of ores in it tears through the stack of ores in a couple seconds, also destroying all of them.

I felt a video would best demonstrate this: [http://share.coros.us/files/tinkerio-orecrusher.m4v](http://share.coros.us/files/tinkerio-orecrusher.m4v)

Using version: 1.12.2-rw2.7.1

**Comment by gkbm2013** [comment]
The issue was solved in commit 516cc30ff40a34ccc83a4115af1360c81d715229. Thanks for report the issue.
