### ISSUE TITLE
Breaking a fuel input machine in any way will not drop the item inside of it

### ISSUE THREAD

**Issue by itsyaboiedchoi** [gkbm2013/tinker-IO#95]
I know that there Is a current bug where the fuel input machine will break instantly, but putting any fuel in it, then breaking it, even with a pickaxe, it will not drop the fuel and only drop the machine.

**Comment by gkbm2013** [comment]
Could you provide the version of Tinker I/O that you installed? Thanks!

**Comment by gkbm2013** [comment]
The issue was solved. Thanks for  the report.
