### ISSUE TITLE
Block of Cobalt has some wrong ore dictionaries, when installed Tinker IO

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [gkbm2013/tinker-IO#97]
Mods list:
1. Tinker IO: 1.12.2-rw2.7.1
2. RedstoneFlux: 1.12-2.1.0.6
3. Mantle: 1.3.3.55
4. Tinkers Construct: 2.13.0.171

Details: https://github.com/SlimeKnights/TinkersConstruct/issues/3986

**Comment by gkbm2013** [comment]
The problem is solved in commit f3d08037ec412b33bcbbe9ae16cc2b536102ffda. Thanks for reporting the issue. This thread will be closed after the new version of Tinker I/O is released.
