### ISSUE TITLE
Idle Smart Output still using server resources

### ISSUE THREAD

**Issue by Keaft** [gkbm2013/tinker-IO#98]
Using LagGoggles I noticed that the Smart Output even when it's not doing anything still takes up server resources.

It has a Slot Upgrade I, an Ingot Cast, and no fluid in it's internal tank.

Not sure if it still functions that way even if the only 3 mods installed are the Tinkers Construct, Tinker I/O, and LagGoggles.
![2020-04-17_04 35 10](https://user-images.githubusercontent.com/68153/79560540-04df0b80-8065-11ea-9917-895a8674593e.png)

Edit: Can confirm this is the case with just those 3 mods installed and no upgrades.

**Comment by gkbm2013** [comment]
Thanks for the report. I think the performance of Smart Output should be optimized. I will try to fix it in the next version.

**Comment by gkbm2013** [comment]
Hi! The performance of Smart Output is improved in Tinker I/O RW 2.8.3. The new version will released in the next few days.

TPS when casting:
![image](https://user-images.githubusercontent.com/11485888/97776354-49b23600-1ba2-11eb-98e2-5119427d3102.png)


TPS when idle:
![image](https://user-images.githubusercontent.com/11485888/97776321-0b1c7b80-1ba2-11eb-8d3e-1dc27b66bf18.png)

Thanks for your report again!

**Comment by Keaft** [comment]
Hey thank you! That's really exciting! Great work and thank you for such a simple yet powerful mod. It really helps with the feel and flow of tinkers. Pun intended! :laughing:

**Comment by gkbm2013** [comment]
Tinker I/O rw 2.8.3 is released, so I close this GitHub issue. If there are any performance issues about Smart Output, feel free to open a new GitHub issue or reopen this issue. Thanks!
